main: xyz.msws.supergive.SuperGive
name: SuperGive
version: 1.0.1
author: MSWS
api-version: 1.13
description: Improved give command
permissions:
  supergive.*:
    description: Full Access to SuperGive
    children:
      supergive.command.loadout: true
      supergive.command.give: true
      supergive.command.give.*: true
      supergive.command.generate: true
      supergive.command.reset: true
      supergive.attribute.*: true
  supergive.command.give:
    description: Access to the /give command
    children:
      supergive.command.give.hand: true
      supergive.command.give.inventory: true
      supergive.command.give.unsafeenchants: true
      supergive.command.give.*: true
  supergive.selector.*:
    descriptor: Access to all selectors
    children:
      supergive.selector.annotated.world: true
      supergive.selector.annotated.worldplayers: true
      supergive.selector.annotated.all: true
      supergive.selector.annotated.players: true
      supergive.selector.annotated.self: true
      supergive.selector.annotated.gamemode: true
      supergive.selector.annotated.entitytype: true
      supergive.selector.permission: true
      supergive.selector.radius: true
      supergive.selector.vanilla: true
      supergive.selector.world: true
      supergive.selector.world.*: true
  supergive.attribute.*:
    descriptor: Access to all attributes
    children:
      supergive.attribute.contents: true
      supergive.attribute.damage: true
      supergive.attribute.enchantment: true
      supergive.attribute.entity: true
      supergive.attribute.itemflag: true
      supergive.attribute.lore: true
      supergive.attribute.name: true
      supergive.attribute.owner: true
      supergive.attribute.pattern: true
      supergive.attribute.potion: true
      supergive.attribute.stored: true
      supergive.attribute.unbreakable: true
      supergive.attribute.contents: true
      supergive.attribute.command: true
  supergive.command.loadout:
    description: Access to the /loadout command
    children:
      supergive.command.loadout.create: true
      supergive.command.loadout.edit: true
      supergive.command.loadout.delete: true
  supergive.command.generate:
    description: Access to the /generate command
    default: true
  supergive.command.reset:
    description: Access to reset config and lang files
